shared:
  vm-fleet:
    type: vm-fleet
    params:
      app_id: "todo-app"
      env_id: "dev"
      instance_count: 2
      instance_type: "t3.micro"
      startup_script: |
        #!/bin/bash
        set -e
        
        # Log everything
        exec > >(tee /var/log/user-data.log) 2>&1
        echo "=== Todo App VM Setup Started at $(date) ==="
        
        # Update system
        apt-get update -y
        apt-get install -y curl git
        
        # Install Node.js 18
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt-get install -y nodejs
        
        # Verify installation
        node --version
        npm --version
        
        # Create app user and directory
        useradd -m -s /bin/bash todoapp
        mkdir -p /home/todoapp/app
        
        # Clone the fresh todo app
        cd /home/todoapp
        git clone https://github.com/DemoKaspar/fresh-todo-app.git app
        cd app
        
        # Install dependencies
        npm install --production
        
        # Set ownership
        chown -R todoapp:todoapp /home/todoapp
        
        # Create systemd service
        cat > /etc/systemd/system/todoapp.service << EOF
        [Unit]
        Description=Todo App
        After=network.target
        
        [Service]
        Type=simple
        User=todoapp
        WorkingDirectory=/home/todoapp/app
        ExecStart=/usr/bin/node server.js
        Restart=always
        RestartSec=10
        Environment=PORT=3000
        Environment=NODE_ENV=production
        
        [Install]
        WantedBy=multi-user.target
        EOF
        
        # Start service
        systemctl daemon-reload
        systemctl enable todoapp
        systemctl start todoapp
        
        # Verify it's running
        sleep 5
        systemctl status todoapp
        
        # Test health endpoint
        for i in {1..20}; do
            if curl -f http://localhost:3000/health; then
                echo "=== Todo App is healthy! ==="
                break
            fi
            echo "Waiting for app to start... ($i/20)"
            sleep 3
        done
        
        echo "=== Setup completed at $(date) ==="

workloads: {}