shared:
  vm-fleet:
    type: vm-fleet
    params:
      app_id: "todo-app"
      env_id: "${humanitec.env_id}"
      container_image: "ghcr.io/demokaspar/fresh-todo-app:staging"
      container_port: 3000

workloads:
  todo-app:
    variables:
      LOAD_BALANCER_URL: "http://${shared.vm-fleet.outputs.loadbalancer_ip}"
      NODE_ENV: "staging"