name: Deploy Todo App

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  HUMANITEC_ORG: unveiled-lunchroom-defame-ki2k
  PROJECT_ID: humanitec-11wcie-vm-project
  ENVIRONMENT_ID: dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Install Humanitec CLI
      run: |
        curl -L -o hctl_linux_amd64.tar.gz https://github.com/humanitec/hctl/releases/download/v1.41.0/hctl_1.41.0_linux_amd64.tar.gz
        tar -xzf hctl_linux_amd64.tar.gz
        sudo install -o root -g root -m 0755 hctl /usr/local/bin/hctl
        hctl --version

    - name: Deploy to Humanitec
      env:
        HUMANITEC_AUTH_TOKEN: ${{ secrets.HUMANITEC_TOKEN }}
      run: |
        echo "Deploying fresh todo app..."
        echo "Organization: $HUMANITEC_ORG"
        echo "Project: $PROJECT_ID"
        echo "Environment: $ENVIRONMENT_ID"
        
        hctl deploy $PROJECT_ID $ENVIRONMENT_ID deployment.yaml --no-prompt --runner-logs-level debug